### PR TITLE
Compile warning fixes

### PR DESCRIPTION
**Pull request by xavierba**
Patch from Stuart D. Gathman (@sdgathman)

### CODE REVIEW

**Review by sdgathman — CHANGES_REQUESTED** [review]
_GNU_SOURCE might not be portable to all systems.
packet_time and current_time were never set, so packet_age was random.  Now it is 0L, but that is not so good either.  I wasn't ready to submit these patches yet.

**Comment by xavierba** [comment]
Oops, sorry Stuart, my apologies, I was too hasty to clean items from my tasks list.
I close this PR and let you resubmit when you're happy with the patch.

**Comment by xavierba** [comment]
Let's re-open this.
@sdgathman, can you please update the patch if you have spare cycles ?

**Comment by xavierba** [comment]
Rebased on top of maint branch.

**Review by hedenface — APPROVED** [review]
Looks good to me.

**Review by hedenface — APPROVED** [review]
Looks good

**Pull request merged**
